### ISSUE TITLE
Plugin interferes with RSS feeds

### ISSUE THREAD

**Issue by stefanjudis** [jdvivar/eleventy-plugin-add-web-component-definitions#11]
Hello Daniel,

first of all, thank you so much for the plugin. It does exactly what I was looking for and it saved me a lot of work. Great work! Thank you! ♥️

Unfortunately, I'm running into a small issue. I use eleventy to also generate RSS feeds and since I enabled the plugin my RSS broke. 🙈

I debugged a little bit and saw that the plugin changes files with the file type `html` or files that start with `<`. The 2nd condition is true for RSS feeds and that leads to malformed feed files. 

https://github.com/jdvivar/eleventy-plugin-add-web-component-definitions/blob/master/add-web-component-definitions.js#L25

To solve the issue I see two options:

1. add an `ignore` glob config option
2. change the 2nd condition to `content.toLowerCase().startsWith('<!doctype html')` (not sure if that's a breaking change though).

Thanks so much for the hard work, and I'm also happy to hand in a PR if you prefer that.

**Comment by jdvivar** [comment]
Thanks for your message, I'll take a look as soon as I can and get back to you.

**Comment by stefanjudis** [comment]
No rush, I'm using my fork right now. :) All smooth!

**Comment by jdvivar** [comment]
Hi @stefanjudis, thanks for your bug report.
I added a test specifically for a case like yours and indeed it failed at first. I fixed just with one line 🕺

Eleventy would be more performant building a site with an ignore glob as option in this plugin as you suggested, but that would add more boilerplate. I would consider it if more edge cases like this one keep breaking.

Can you please try again with the new version I just published (2.0.3) and tell me how it goes?

Feel free to reopen if something goes wrong

**Comment by jdvivar** [comment]
Also, I'm sure the previous version will also work just fine (v2.0.1). See this discussion if you're curious on why I had to introduce the process of files that start with `<`:

https://github.com/jdvivar/eleventy-plugin-add-web-component-definitions/issues/9

**Comment by stefanjudis** [comment]
I upgraded to `^v2.0.0` and things seem to run smoothly. Thanks @jdvivar. 🙇‍♂️
