### ISSUE TITLE
passing eleventyConfig to path functions

### ISSUE THREAD

**Issue by bennypowers** [jdvivar/eleventy-plugin-add-web-component-definitions#21]
What do you think of passing in the config object?

```js
eleventyConfig.addPlugin(addWebComponentDefinitions, {
  path: (tag, config) => config.environment === 'production'
      ? `/my-project/components/${tag}.js`
      : `/components/${tag}.js`
  }
)
```
```js
eleventyConfig.addPlugin(addWebComponentDefinitions, {
  specifiers: {
    'custom-tag-one': (tag, config) => `/${config.pathPrefix}/assets/${tag}.js`,
    'custom-tag-two': 'my-module'
  }
)
```

**Comment by jdvivar** [comment]
Hi @bennypowers 

Can you elaborate? You mean just as a way to improve the examples shown on the documentation?

**Comment by bennypowers** [comment]
sure, so here
https://github.com/jdvivar/eleventy-plugin-add-web-component-definitions/blob/1520fb1e2be9c415e1286a2be61b1e84b8906fc7/index.js#L7
we have access to the config object

maybe the user would also like to have access to that object in the path function?

in which case we'd pass the eleventyConfig along as well as the options

**Comment by jdvivar** [comment]
But when you're applying the filter, you already have access to your config, haven't you? (in the examples I used the name `project` following the documentation of Eleventy at that time though)
```js
eleventyConfig.addPlugin(addWebComponentDefinitions, {
  path: tag => config.environment === 'production'
      ? `/my-project/components/${tag}.js`
      : `/components/${tag}.js`
  }
)
```
I can't see the value right now, although there must be one if you are proposing it. Care to send a pull request?
