### ISSUE TITLE
Would you take a PR to replace JSDom with parse5?

### ISSUE THREAD

**Issue by bennypowers** [jdvivar/eleventy-plugin-add-web-component-definitions#4]
Howdy

I put together an alternate implementation that uses parse5 and hast instead of JSDom, and is quite performant.

Rather than publish under some other name, would you be interested in taking a PR?

**Comment by jdvivar** [comment]
Hi Benny! I know and follow you on Twitter!

Of course!

By the way I did this a bit in a whim, if you find any other way to improve it, please tell

**Comment by jdvivar** [comment]
Closing as it's merged now, see #5
