### ISSUE TITLE
Dead filter

### ISSUE THREAD

**Issue by gdbaldw** [jdvivar/eleventy-plugin-add-web-component-definitions#6]
https://github.com/jdvivar/eleventy-plugin-add-web-component-definitions/blob/3cdf1df4036e49fc41a9e78e14a898a5a830a6e6/add-web-component-definitions.js#L66

...is now dead (unless path is a null string, which could/should be another throw Error), and the line can be deleted, because of this improvement...

https://github.com/jdvivar/eleventy-plugin-add-web-component-definitions/blob/3cdf1df4036e49fc41a9e78e14a898a5a830a6e6/add-web-component-definitions.js#L61

**Comment by bennypowers** [comment]
possibly related, but now with 
```js
    eleventyConfig.addPlugin(addWebComponentDefinitions, {
      specifiers: {
        'code-copy': importSpecifier,
        'code-tabs': importSpecifier,
        'x-tabs': importSpecifier,
        'wcd-snippet': importSpecifier,
        'type-doc': importSpecifier,
        'codesandbox-button': '@power-elements/codesandbox-button',
      },
    });
```

I get a lot of 
```
[add-web-component-definitions] /js/components/launch-dark-switch/launch-dark-switch.js
[add-web-component-definitions] /js/components/rocket-search/rocket-search.js
[add-web-component-definitions] /js/components/rocket-drawer/rocket-drawer.js
[add-web-component-definitions] /js/components/rocket-navigation/rocket-navigation.js
```

for components that I *dont* want to auto-import.

I recommend that *either* path *or* specifiers be allowed. if both are defined, throw an error, if specifiers is defined, only process those tagnames which are configured.

**Comment by gdbaldw** [comment]
@bennypowers can you try setting path to an empty string, `""`. Then, the Boolean filter will will filter it out. If that works for you, we can keep the Boolean filter, and simply update the documentation.

**Comment by jdvivar** [comment]
@bennypowers 

I have accepted the merge, however I think a specifiers array only makes sense as it was added by @gdbaldw in the first place. It wasn't really needed, but I understood the requirement to have a function for all and a specifiers object for some tags. However if we either have a specifiers object or a path function... why not just a path function which will reduce complexity? I can add examples in the documentation to use the function like this, which will work for your need

What do you think?

```js
eleventyConfig.addPlugin(addWebComponentDefinitions, {
      path: tag => {
        const specifiers = {
          'code-copy': importSpecifier,
          'code-tabs': importSpecifier,
          'x-tabs': importSpecifier,
          'wcd-snippet': importSpecifier,
          'type-doc': importSpecifier,
          'codesandbox-button': '@power-elements/codesandbox-button',
        }
        return specifiers[tag]
    });
```

**Comment by bennypowers** [comment]
yeah, I mean it's six-of-one-half-a-dozen-of-the-other

however, the advantage of the specifiers list is that it's more declarative. In a config file, I expect to use a function only when some dynamism is required, e.g. when the path name depends on the tag name. Whereas, if the path name is static, I would expect to be able to just pass a POJO. It's a matter of what the config interface communicates to the user.
