### ISSUE TITLE
Deal with `permalink: false`

### ISSUE THREAD

**Issue by bennypowers** [jdvivar/eleventy-plugin-add-web-component-definitions#9]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `eleventy-plugin-add-web-component-definitions@2.0.1` for the project I'm working on because templates with `permalink: false` cause an error when running the package.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/eleventy-plugin-add-web-component-definitions/add-web-component-definitions.js b/node_modules/eleventy-plugin-add-web-component-definitions/add-web-component-definitions.js
index 2fbc2d6..da3ac31 100644
--- a/node_modules/eleventy-plugin-add-web-component-definitions/add-web-component-definitions.js
+++ b/node_modules/eleventy-plugin-add-web-component-definitions/add-web-component-definitions.js
@@ -16,6 +16,9 @@ const addChild = (body, child, position) => {
 }
 
 module.exports = function (options, content, outputPath) {
+  if (typeof outputPath !== 'string')
+    return content;
+    
   if (!!options.path && !!options.specifiers) {
     throw new Error('You may configure a path function or import specifiers, but not both')
   }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by jdvivar** [comment]
What a great tool is patch-package! I didn't know it until now 😀
Fixing it 🛠

**Comment by jdvivar** [comment]
@bennypowers 
What if your permalink actually doesn't end with html?

In the demo:
```
---
permalink: "whatever"
---
<custom-tag></custom-tag>
```

I also asked in https://github.com/11ty/eleventy/issues/653

**Comment by bennypowers** [comment]
> What a great tool is patch-package! I didn't know it until now 😀
> Fixing it 🛠

I know, right?

>  What if your permalink actually doesn't end with html?

I dunno, really, but maybe that's a separate issue?

**Comment by jdvivar** [comment]
I think I've found a good balance, tell me if it works well for you in your projects
